protected/controllers/IdeasController.php
<?php

class IdeasController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'nulls', 'week', 'view', 'downloadfile', 'create', 'update'),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $model = $this->loadModel($id);
        if ( isset( $_POST['Reply'] ) ) {
            $newComment = new Comments();
            $newComment->date = new CDbExpression('NOW()');
            $newComment->idea_id = $model->id;
            $newComment->user_id = Yii::app()->user->getId();
            $newComment->content = $_POST['Comments']['content'];
            $newComment->parent_comment_id = $_POST['comment_parent'];
            if ( ! $newComment->save() ) echo 'ERROR!';

        }
        $comments = $model->getComments();
        $model_attachments = new Attachments();
        $attachments = $model_attachments->findAllByAttributes(array('idea_id' => $id));

        $this->render('view', array(
            'attachments' => $attachments,
            'model' => $model,
            'comments' => $comments,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Ideas;

        if (isset($_POST['Ideas'])) {
            $attachments = CUploadedFile::getInstancesByName('attachments');
            $model->attributes = $_POST['Ideas'];
            $model->date = new CDbExpression('NOW()');
            $model->user_id = Yii::app()->user->getId();


            if ($model->save()) {
                if ($attachments) {

                    foreach ($attachments as $key => $attachment) {
                        $ext = pathinfo($attachment);
                        $newAttachment = new Attachments();
                        $newAttachment->idea_id = $model->id;
                        $newAttachment->name = md5($attachment) . '.' . $ext['extension'];
                        $newAttachment->original_name = $attachment;

                        if ($newAttachment->save()) {
                            $attachment->saveAs(Yii::getPathOfAlias('webroot') . '/attachments/' . md5($attachment) . '.' . $ext['extension']);
                        }
                    }
                }

                $email = Yii::app()->email;
                $email->to = 'webfix@ukr.net';//'webmaster@example.com';
                $email->subject = 'New Idea';
                $email->view = 'myview';
                $var1 = Yii::app()->request->getBaseUrl(true).'/ideas/'.$model->id;
                $title = $model->title;
                $name = Yii::app()->user->getName();
                $email->viewVars = array('var1'=>$var1, 'title'=>$title, 'name'=>$name);
                $email->send();

                $this->redirect(array('view', 'id' => $model->id));



            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);

        if (isset($_POST['Ideas'])) {
            $attachments = CUploadedFile::getInstancesByName('attachments');
            $model->attributes = $_POST['Ideas'];

            if ($model->save()) {
                if ($attachments) {
                    foreach ($attachments as $key => $attachment) {
                        $ext = pathinfo($attachment);
                        $newAttachment = new Attachments();
                        $newAttachment->idea_id = $model->id;
                        $newAttachment->name = md5($attachment) . '.' . $ext['extension'];
                        $newAttachment->original_name = $attachment;

                        if ($newAttachment->save()) {
                            $attachment->saveAs(Yii::getPathOfAlias('webroot') . '/attachments/' . md5($attachment) . '.' . $ext['extension']);
                        }
                    }
                }
                $this->redirect(array('view', 'id' => $model->id));

            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        if ( Yii::app()->user->isGuest )
            $this->redirect( array('site/login') );

        $criteria=new CDbCriteria(array('order'=> 'id DESC'));
        $count=Ideas::model()->count($criteria);
        $pages=new CPagination($count);
        $pages->pageSize=10;
        $pages->applyLimit($criteria);
        $data=Ideas::model()->findAll($criteria);

        $model = new Likes();
        $like = $model->findAll(array(
            'select'=>'id, idea_id',
            'condition'=>'user_id=:user_id',
            'params'=>array(':user_id'=>Yii::app()->user->id)));
        $likesArray = CHtml::listData($like, 'id', 'idea_id');

        $model = new Users();
        $users= $model->findAll();
        $this->render('index', array(
            'ideas' => $data,
            'userLikes' => $likesArray,
            'author' => $users,
            'pages' => $pages
        ));
    }

    public function actionNulls()
    {
        if ( Yii::app()->user->isGuest )
            $this->redirect( array('site/login') );

        $criteria=new CDbCriteria();
        $criteria->with = (array('relatedLikes'=>array(
            'select' => 'relatedLikes.idea_id AS t1_c2',
            'group' => 't.id',
            'having' => 'COUNT(relatedLikes.idea_id) = 0',
        )));

                $count=Ideas::model()->count($criteria);
                //$pages=new CPagination($count);
                // results per page
                $pages=new CPagination($count);
                $pages->pageSize=10;
                $pages->applyLimit($criteria);

        $model = new Ideas();

        $data = $model->with(array('relatedLikes'=>array(
                'select' => 'relatedLikes.idea_id AS t1_c2',
                'group' => 't.id',
                'having' => 'COUNT(relatedLikes.idea_id) = 0',
            )))->findAll();

        /*----------------------------------------------------------------------------------------------------*
        $criteria=new CDbCriteria();
        $pages=new CPagination($data);
        $pages->pageSize=10;
        $pages->applyLimit($criteria);
        /*----------------------------------------------------------------------------------------------------*/

        $model = new Likes();
        $like = $model->findAll(array(
            'select'=>'id, idea_id',
            'condition'=>'user_id=:user_id',
            'params'=>array(':user_id'=>Yii::app()->user->id)));
        $likesArray = CHtml::listData($like, 'id', 'idea_id');

//        var_dump(array_search('12', $likesArray));
//        foreach ($data as $key => $value) {
//            (array_search('12', $likesArray) != false) ? $data[$key]->userLike = true : $data[$key]->userLike = false;
//        }
//        print_r($data);

        $this->render('index', array(
            'ideas' => $data,
            'userLikes' => $likesArray,
            'pages' => $pages
        ));
    }

    public function actionWeek()
    {
        if ( Yii::app()->user->isGuest )
            $this->redirect( array('site/login') );

        $criteria=new CDbCriteria(array('order'=> 'id DESC','condition'=>'date >= DATE_SUB(CURRENT_DATE, INTERVAL 7 DAY)'));
        $count=Ideas::model()->count($criteria);
        $pages=new CPagination($count);
        $pages->pageSize=10;
        $pages->applyLimit($criteria);
        $data=Ideas::model()->findAll($criteria);

        $model = new Likes();
        $like = $model->findAll(array(
            'select'=>'id, idea_id',
            'condition'=>'user_id=:user_id',
            'params'=>array(':user_id'=>Yii::app()->user->id)));
        $likesArray = CHtml::listData($like, 'id', 'idea_id');

//        var_dump(array_search('12', $likesArray));
//
//        foreach ($data as $key => $value) {
//            (array_search('12', $likesArray) != false) ? $data[$key]->userLike = true : $data[$key]->userLike = false;
//        }
//        print_r($data);

        $this->render('index', array(
            'ideas' => $data,
            'userLikes' => $likesArray,
            'pages' => $pages
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Ideas the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Ideas::model()->findByPk($id);
        if ($model === null)

protected/controllers/UsersController.php
<?php

class UsersController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
            array('allow',
                'actions'=>array('view', 'index'),
                'users'=>array('*'),
            ),

            array('allow',
                'actions'=>array('edit','profile'),
                'users'=>array('@'),
            ),

			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

    public function actionProfile()
	{
        $id = Yii::app()->user->id;
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }

    public function actionIndex()
    {
        $model=new Users();
        $users=$model->findAll();
        $this->render('index',array(
            'model'=>$users,
        ));
    }


    public function actionEdit()
    {
        $id = Yii::app()->user->id;
        $model = $this->loadModel($id);
        $origdata = Users::model()->findByPk($id);

        if (isset($_POST['Users'])) {
            $userID = Yii::app()->user->id;
            $userName = Yii::app()->user->name;
            $model->attributes = $_POST['Users'];
            $uploadedFile=CUploadedFile::getInstance($model,'image');
            if ($model->password !== $origdata->password ){$model->password = sha1( $model->password );}
            $fileName = "{$userID}-{$userName}";  // random number + file name
            $fileName = md5($fileName);
            $model->image = $fileName.'.jpg';

            if(!empty($uploadedFile))  // check if uploaded file is set or not
            {
                $model->image = $fileName.'.jpg';
                $uploadedFile->saveAs(Yii::app()->basePath.'/../users_img/'.$fileName.'.jpg');
                $image = Yii::app()->image->load(Yii::app()->basePath.'/../users_img/'.$fileName.'.jpg');
                $image->quality(75);
                $image->resize(300,300);
                $image->crop(200, 200);
                $image->save(Yii::app()->basePath.'/../users_img/small/'.$fileName.'.jpg'); // or $image->save('images/small.jpg');
            }

            if ($model->save()) {
                $this->redirect(array('profile', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Users the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Users::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Users $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='users-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content" class="clearfix">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
    <div class="col-md-2 nopaddingmarg" style="margin-bottom: 50px">
            <ul class="nav nav-pills nav-stacked">
            <li><a href="<?= Yii::app()->createUrl("/ideas/create");?>" class="list-group-item active">Create Idea</a></li>
            <li><a href="<?= Yii::app()->createUrl("/ideas/nulls");?>" class="list-group-item">Null Likes Idea</a></li>
            <li><a href="<?= Yii::app()->createUrl("/ideas/week");?>" class="list-group-item">Last Week Ideas</a></li>
            <li><a href="<?= Yii::app()->createUrl("/users/index");?>" class="list-group-item">All users</a></li>
        </ul>
    </div>
    <div class="col-md-10">
        <?php echo $content; ?>
    </div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/font-awesome.min.css" media="screen, projection" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/bootstrap/css/bootstrap.min.css" media="screen, projection" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/panel_idea.css" media="screen, projection" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/nicolas.css" media="screen, projection" />
    <link href='http://fonts.googleapis.com/css?family=Comfortaa|Philosopher|Roboto&subset=latin,cyrillic' rel='stylesheet' type='text/css'>

    <script src="https://code.jquery.com/jquery-1.8.3.min.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery.scrollUp.min.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/bootstrap/js/bootstrap.min.js"></script>
<!--    <script src="--><?php //echo Yii::app()->request->baseUrl; ?><!--/bootstrap/js/bootswatch.js"></script>-->
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/customscript.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/main_idea.js"></script>
</head>

<body>
    <div class="navbar navbar-default navbar">
        <div class="container">
            <div class="navbar-header">
                <a href="<?php echo Yii::app()->homeUrl?>" >
                    <img class="navbar-brand" src="<?php echo Yii::app()->request->baseUrl; ?>/bootstrap/img/logo.png" style="padding-left: 0px;" height="500">
                </a>
            </div>
            <div class="navbar-collapse collapse" id="navbar-main">
                <?php $this->widget('zii.widgets.CMenu',array(
                    'htmlOptions' => array( 'class' => 'nav navbar-nav'),
                    'items'=>array(
                        array('label'=>'Home','class' => 'active', 'url'=>Yii::app()->homeUrl),
                       // array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
                       // array('label'=>'Contact', 'url'=>array('/site/contact')),
                       // array('label'=>'Chat', 'url'=>array('/site/page', 'view'=>'chat'), 'visible'=>!Yii::app()->user->isGuest),
                        array('label'=>'Profile', 'url'=>array('/users/profile'), 'visible'=>!Yii::app()->user->isGuest),
                        array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest),
                    ))); ?>
            </div>
        </div>
    </div>

    <div class="container" id="page">
	    <?php if(isset($this->breadcrumbs)):?>
        <div class="row">
            <div id="bc1" class="btn-group btn-breadcrumb angles">
                <?php $this->widget('ext.MyBreadcrumb.MyCBreadcrumbs', array(
		        'links'=>$this->breadcrumbs,
		        )); ?>
            </div>
        </div>
        <?php endif?>

        <div class="row" style="margin-top: 20px;">
            <?php echo $content; ?>
        </div>

	    <div class="clear"></div>

        <div class="row">
            <div class="col-lg-12">
                <hr>
                <p><img src="<?php echo Yii::app()->request->baseUrl; ?>/bootstrap/img/logo.png" height="20" style="padding-right: 20px;">Powered by <a href="http://faceit-team.com" rel="nofollow">FaceIT</a>.</p>
            </div>
        </div>




    </div><!-- page -->
</body>
</html>