protected/models/Users.php
<?php

/**
 * This is the model class for table "tbl_users".
 *
 * The followings are the available columns in table 'tbl_users':
 * @property integer $id
 * @property integer $role
 * @property string $login
 * @property string $password
 * @property string $name
 * @property string $email
 * @property string $specialization
 * @property integer $office_number
 * @property string $image
 * @property integer $status_confirmed
 * @property integer $ban
 */
class Users extends CActiveRecord
{
	public $errorMessage;
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_users';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('role, login, password, status_confirmed', 'required'),
			array( 'login', 'unique' ),
			array('role, office_number, status_confirmed, ban', 'numerical', 'integerOnly'=>true),
			array('login, specialization', 'length', 'max'=>25),
			array('password', 'length', 'max'=>40),
			array('name, email', 'length', 'max'=>50),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, role, roleName.name, login, password, name, email, specialization, office_number, image, status_confirmed, ban', 'safe', 'on'=>'search'),
            array('image', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true, 'on'=>'insert,update'), // this will allow empty field when page is update (remember here i create scenario update)
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
            'roleName' => array(self::BELONGS_TO, 'Roles', 'role'),
            'userIdeas' => array(self::HAS_MANY, 'Ideas', 'user_id', 'order'=>'id DESC')
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'role' => 'Role',
			'login' => 'Login',
			'password' => 'Password',
			'name' => 'Name',
			'email' => 'Email',
			'specialization' => 'Specialization',
			'office_number' => 'Office Number',
			'image' => 'Image',
			'status_confirmed' => 'Status Confirmed',
			'ban' => 'Ban',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *   ккк
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('role',$this->role);
		$criteria->compare('login',$this->login,true);
		$criteria->compare('password',$this->password,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('specialization',$this->specialization,true);
		$criteria->compare('office_number',$this->office_number);
		/*$criteria->compare('image',$this->image,true);*/
		$criteria->compare('status_confirmed',$this->status_confirmed);
		$criteria->compare('ban',$this->ban);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Users the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function registration( $user ) {
		$this->login = $user['login'];
		$this->password = sha1( $user['password'] );
		$this->status_confirmed = 0;
		$this->role = 1;
		if ( $this->validate() )
			return $this->save();
		else {
			return false;
		}
	}

	public function login() {
		$auth = new UserIdentity( $_POST['Users']['login'], $_POST['Users']['password'] );
		if ( $auth->authenticate() ) {
			Yii::app()->user->login( $auth, 3600*24*30 );
			return true;
		} else {
			$this->errorMessage = $auth->errorCode == 1 ? 'Invalid Username' : 'Invalid Password';
			return false;
		}
	}

}

protected/controllers/UsersController.php
<?php

class UsersController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
            array('allow',
                'actions'=>array('view', 'index'),
                'users'=>array('*'),
            ),

            array('allow',
                'actions'=>array('edit','profile'),
                'users'=>array('@'),
            ),

			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

    public function actionProfile()
	{
        $id = Yii::app()->user->id;
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }

    public function actionIndex()
    {
        $model=new Users();
        $users=$model->findAll();
        $this->render('index',array(
            'model'=>$users,
        ));
    }


    public function actionEdit()
    {
        $id = Yii::app()->user->id;
        $model = $this->loadModel($id);
        $origdata = Users::model()->findByPk($id);

        if (isset($_POST['Users'])) {
            $userID = Yii::app()->user->id;
            $userName = Yii::app()->user->name;
            $model->attributes = $_POST['Users'];
            $uploadedFile=CUploadedFile::getInstance($model,'image');
            if ($model->password !== $origdata->password ){$model->password = sha1( $model->password );}
            $fileName = "{$userID}-{$userName}";  // random number + file name
            $fileName = md5($fileName);
            $model->image = $fileName.'.jpg';

            if(!empty($uploadedFile))  // check if uploaded file is set or not
            {
                $model->image = $fileName.'.jpg';
                $uploadedFile->saveAs(Yii::app()->basePath.'/../users_img/'.$fileName.'.jpg');
                $image = Yii::app()->image->load(Yii::app()->basePath.'/../users_img/'.$fileName.'.jpg');
                $image->quality(75);
                $image->resize(300,300);
                $image->crop(200, 200);
                $image->save(Yii::app()->basePath.'/../users_img/small/'.$fileName.'.jpg'); // or $image->save('images/small.jpg');
            }

            if ($model->save()) {
                $this->redirect(array('profile', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Users the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Users::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Users $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='users-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/users/_form.php
<?php
/* @var $this UsersController */
/* @var $model Users */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'users-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

    <div class="row">
        <?php echo $form->labelEx($model,'name'); ?>
        <?php echo $form->textField($model,'name',array('size'=>50,'maxlength'=>50)); ?>
        <?php echo $form->error($model,'name'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model,'email'); ?>
        <?php echo $form->textField($model,'email',array('size'=>50,'maxlength'=>50)); ?>
        <?php echo $form->error($model,'email'); ?>
    </div>

	<div class="row">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password',array('size'=>40,'maxlength'=>40)); ?>
		<?php echo $form->error($model,'password'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'specialization'); ?>
		<?php echo $form->textField($model,'specialization',array('size'=>25,'maxlength'=>25)); ?>
		<?php echo $form->error($model,'specialization'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'office_number'); ?>
		<?php echo $form->textField($model,'office_number'); ?>
		<?php echo $form->error($model,'office_number'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'image'); ?>
		<?php echo $form->textField($model,'image',array('size'=>50,'maxlength'=>50)); ?>
		<?php echo $form->error($model,'image'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/users/_view.php
<?php
/* @var $this UsersController */
/* @var $data Users */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('role')); ?>:</b>
	<?php echo CHtml::encode($data->role); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('login')); ?>:</b>
	<?php echo CHtml::encode($data->login); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('password')); ?>:</b>
	<?php echo CHtml::encode($data->password); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CHtml::encode($data->email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('specialization')); ?>:</b>
	<?php echo CHtml::encode($data->specialization); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('office_number')); ?>:</b>
	<?php echo CHtml::encode($data->office_number); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('image')); ?>:</b>
	<?php echo CHtml::encode($data->image); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('status_confirmed')); ?>:</b>
	<?php echo CHtml::encode($data->status_confirmed); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('ban')); ?>:</b>
	<?php echo CHtml::encode($data->ban); ?>
	<br />

	*/ ?>

</div>

protected/views/users/index.php
<?php
/* @var $this UsersController */
/* @var $model Users */

    $this->breadcrumbs=array(
	    'Profile'=>array('profile'),
    );
?>
<div class="postmain">
<h1> Users Profiles</h1>

<table id="user_list" class="table table-striped table-hover table-condensed">
    <thead>
    <tr>
        <td>
            <h5>Foto</h5>
        </td>
        <td>
            <h5>Name</h5>
        </td>
        <td>
            <h5>Email</h5>
        </td>
        <td>
            <h5>Specialization</h5>
        </td>
        <td>
            <h5>Office number</h5>
        </td>
    </tr>
    </thead>
    <tbody class="usertblz">
    <?php foreach($model as $uid):?>
        <tr>
            <td>
                <div style="height: 50px;">
                    <?php if (isset ($uid->image)) {
                        echo CHtml::image(Yii::app()->request->baseUrl.'/users_img/small/'.$uid->image, "User foto", array('class'=>'img-thumbnail', 'width'=>'50'));}
                    else {
                        echo CHtml::image(Yii::app()->request->baseUrl.'/users_img/default_user.png', "Default foto", array('class'=>'img-thumbnail', 'width'=>'50'));}
                    ?>
                </div>
            </td>

                <?php if(isset($uid->name) or isset($uid->email) or isset($uid->specialization) or isset($uid->office_number) ):?>
            <td>
                <a href='<?php echo Yii::app()->createUrl("/users/view/".$uid->id) ?>'><?php echo $uid->name;?></a>
            </td>
            <td>
                <?php echo $uid->email ?>
            </td>
            <td>
                <?php echo $uid->specialization ?>
            </td>
            <td>
                <?php echo $uid->office_number ?>
            </td>
                <?php else:?>
            <td colspan="4" style="vertical-align: middle; color:#959595">
                User has not filled their profile
            </td>
                <?php endif?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
</div>

protected/views/users/update.php
<?php $this->breadcrumbs=array(
'Profile'=>array('profile') ,
'Edit'=>array('edit') ,
);?>
<div class="postmain clearfix">
    <header>
        <h1>Edit: <?php echo $model->name;?></h1>
    </header>
<div class="form">

    <?php $form=$this->beginWidget('CActiveForm', array(
        'id'=>'users-form',
        // Please note: When you enable ajax validation, make sure the corresponding
        // controller action is handling ajax validation correctly.
        // There is a call to performAjaxValidation() commented in generated controller code.
        // See class documentation of CActiveForm for details on this.
        'enableAjaxValidation'=>false,
        'htmlOptions' => array('enctype' => 'multipart/form-data')
    )); ?>

    <?php echo $form->errorSummary($model); ?>


    <div class="form-group" style="padding-left: 15px">
        <?php if (isset ($model->image)) {
            echo CHtml::image(Yii::app()->request->baseUrl.'/users_img/small/'.$model->image, "User foto",array("width"=>200, 'class'=>'img-thumbnail'));}
        else {
            echo CHtml::image(Yii::app()->request->baseUrl.'/users_img/default_user.png', "Default foto",array("width"=>200, 'class'=>'img-thumbnail'));} ?>
    </div>
 <!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->

    <div class="form-group">
        <div class="row">
            <?php echo $form->labelEx($model,'name', array('class' => 'col-md-2',)); ?>
            <div class="col-lg-7">
                <?php echo $form->textField($model,'name',array('class' => 'col-md-10 form-control', 'id'=>'inputDefault','size'=>50,'maxlength'=>50,'placeholder'=>'Name')); ?>
            </div>
            <?php echo $form->error($model,'name', array('class' => 'btn btn-primary',)); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <?php echo $form->labelEx($model,'email', array('class' => 'col-md-2',)); ?>
            <div class="col-lg-7">
                <?php echo $form->emailField($model,'email',array('class' => 'col-md-10 form-control', 'id'=>'inputDefault','size'=>50,'maxlength'=>50,'placeholder'=>'Email')); ?>
            </div>
            <?php echo $form->error($model,'email', array('class' => 'btn btn-primary',)); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <?php echo $form->labelEx($model,'Password', array('class' => 'col-md-2',)); ?>
            <div class="col-lg-7">
                <?php echo $form->passwordField($model,'password',array('class' => 'col-md-10 form-control', 'id'=>'inputDefault','size'=>50,'maxlength'=>50,'placeholder'=>'Password')); ?>
            </div>
            <?php echo $form->error($model,'password', array('class' => 'btn btn-primary',)); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <?php echo $form->labelEx($model,'image', array('class' => 'col-md-2',)); ?>
            <div class="col-lg-7">
                <?php echo CHtml::activeFileField($model, 'image', array('class' => 'col-md-10')); ?>
            </div>
            <?php echo $form->error($model,'image', array('class' => 'btn btn-primary',)); ?>
        </div>
    </div>


    <div class="form-group">
        <div class="row">
            <?php echo $form->labelEx($model,'specialization', array('class' => 'col-md-2',)); ?>
            <div class="col-lg-7">
                <?php echo $form->textfield($model,'specialization',array('class' => 'col-md-10 form-control','placeholder'=>'Specialization')); ?>
            </div>
            <?php echo $form->error($model,'specialization', array('class' => 'btn btn-primary',)); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <?php echo $form->labelEx($model,'office_number', array('class' => 'col-md-2',)); ?>
            <div class="col-lg-2">
                <?php echo $form->dropDownList($model, 'office_number', array(
                    '1' => '1',
                    '2' => '2',
                    '3' => '3',
                    '4' => '4',
                    '5' => '5',
                    '6' => '6',
                ), array('class' => 'col-md-10 form-control')) ?>
            </div>
        </div>
    </div>


<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
      <div class="row buttons col-md-2">
        <?php echo CHtml::submitButton('Save', array('class' => 'btn btn-primary',) ); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

</div>

protected/views/users/view.php
<?php
/* @var $this UsersController */
/* @var $model Users */

$this->breadcrumbs=array(
    'Profile'=>array('profile'),
);
?>
<div class="postmain clearfix">
<header>
    <h1>Profile: <?php echo $model->name;?></h1>
</header>
<div class="col-md-6 user">
    <div class="row">
        <?php if (isset ($model->image)) {
            echo CHtml::image(Yii::app()->request->baseUrl.'/users_img/small/'.$model->image, "User foto", array('class'=>'img-thumbnail'));}
        else {
            echo CHtml::image(Yii::app()->request->baseUrl.'/users_img/default_user.png', "Default foto", array('class'=>'img-thumbnail'));} ?>
    </div>

    <div class="row">
        <div class="col-md-5"><strong>Login:</strong></div>
        <div class="col-md-7"><?php echo $model->login; ?></div>
    </div>

    <?php if ($model->name): ?>
    <div class="row">
        <div class="col-md-5"><strong>Name:</strong></div>
        <div class="col-md-7"><?php echo $model->name; ?></div>
    </div>
    <?php endif ?>

    <?php if ($model->email): ?>
    <div class="row">
        <div class="col-md-5"><strong>Email:</strong></div>
        <div class="col-md-7"><?php echo $model->email; ?></div>
    </div>
    <?php endif ?>

    <?php if ($model->specialization): ?>
    <div class="row">
        <div class="col-md-5"><strong>Specialization:</strong></div>
        <div class="col-md-7"><?php echo $model->specialization; ?></div>
    </div>
    <?php endif ?>

    <?php if ($model->office_number): ?>
    <div class="row">
        <div class="col-md-5"><strong>Office number:</strong></div>
        <div class="col-md-7"><?php echo $model->office_number; ?></div>
    </div>
    <?php endif ?>

    <div class="row buttons col-md-3">
        <?php if(Yii::app()->user->getId() == $model->id){ ?>
            <a href="<?php echo Yii::app()->createUrl("/users/edit");?>" class="btn btn-primary">Edit</a>
        <?php } ?>
    </div>
</div>

<div class="col-md-6 row usercol">
    <?php if ($model->userIdeas): ?>
    <header><h4>Last 10 ideas</h4></header>
    <?php
        $dddd=0;
        foreach($model->userIdeas as $uid) {
        echo('<div class="row userideas" >');
        echo('<h4><a href="'.Yii::app()->createUrl("/ideas/".$uid->id).'" title="'.$uid->title.'">'.$uid->title.'</a></h4>');
        echo('<small>'.date('d M Y h:i a', strtotime($uid->date)).'</small>');
        if(strlen($uid->content) > 50) {
            $period = strpos($uid->content, '.', 50);
            $teaser = substr($uid->content, 0, $period);
            $teaser = strip_tags($teaser);

            echo('<div class="">'.$teaser.' ...</div>');
        }
        else{
            echo('<div class="">'.strip_tags($uid->content).'</div>');
        }
        echo('</div>');
            if (++$dddd == 10) break;
    } ?>
    <?php endif ?>
</div>
    </div>